language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: TWIG_VERSION=1.24.*

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "twig/twig:${TWIG_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: make test
