language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer update --prefer-dist --no-interaction

script: make test
